version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:13.8.0
    steps: 
       - checkout
       - run: npm i
       - save_cache:
          key: "npm-packages"
          paths:
            - /src/node modules
       - run: npm run lint

  test:    
    docker: 
      - image: circleci/node:13.8.0
    steps: 
       - checkout
       - restore_cache:
          keys: 
            - "npm-packages"
       - run: npm i
       - run: npm run test

  audit:    
    docker: 
      - image: circleci/node:13.8.0
    steps: 
       - checkout
       - run: npm audit

workflows:
  full_cycle:
    jobs:
      - build
      - test:
        requires:
          - build
      -audit:
        requires:
          - test
